// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysamkuzzcnmxmzvpsiho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzYW1rdXp6Y25teG16dnBzaWhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNDk2MjEsImV4cCI6MjA1NzYyNTYyMX0.kekEDTOlAtXMuf18coXnHB5EsPb2CxX39sAuyKXXyFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);